### ISSUE TITLE
Popup Example ?

### ISSUE THREAD

**Issue by Dot2122** [chugcup/Leaflet.draw#2]
Hi, 

First thanks for the example with the compatibility with leaflet RC3.
But do you have some example with popup implementation?

Thanks

**Comment by chugcup** [comment]
Hey @Dot2122, do you mean popups on Markers or other types of shapes?  The README should have an example on how to bind a popup based on the `draw:created` event for Markers.

In the meantime I will try to add an example page that includes popup management (including after edits)

**Comment by chugcup** [comment]
See f7cc20c519a700bb710d78fd9fdd6035871823cd

**Comment by Dot2122** [comment]
Thanks @chugcup for your answer.

I'll check your link.

For information, popup I was talking is popup edition (http://leaflet.github.io/Leaflet.toolbar/examples/popup.html#)
Can I do it with draw:created ?

**Comment by chugcup** [comment]
Ahh I see.  Yes that example you linked to uses the Leaflet.draw library and binds the `L.EditToolbar.Popup` object during the `draw:edited` event.  Since the event API has not changed you should have no problem implementing the same thing

[Leaflet.toolbar/examples/popup.html](https://github.com/Leaflet/Leaflet.toolbar/blob/master/examples/popup.html)

**Comment by Dot2122** [comment]
Yes, but the sample is not working with the lasted version of leaflet.draw.
Because, I think, L.EditToolbar.Popup is not exist in the new version

**Comment by chugcup** [comment]
Hi, it seems that example uses a fork of the main `Leaflet.draw` repository:

https://github.com/justinmanley/Leaflet.draw/tree/leaflet-toolbar-plugin

Since my fork is based off the main repository (and the author never submitted a pull request), the `L.Edit.Popup.Edit` class is not available so that example won't work.  If you wanted to get it integrated you would probably need to copy the extra files from the `src/edit` and `src/draw` folders and try to run it
